const types = {
    FETCH_POSTS: "FETCH_POSTS",
    FETCH_SINGLE_POST: "FETCH_SINGLE_POST",
    FETCH_USERS: "FETCH_USERS",
    FETCH_SINGLE_USER: "FETCH_SINGLE_USER",
    FETCH_ALL_USERS: "FETCH_ALL_USERS",
    CHANGE_SCREEN: "CHANGE_SCREEN",
    FETCH_USERS_POSTS: "FETCH_USERS_POSTS"
}

export default types;
